baby_sitting_jardins:
        resource: "@BabySittingBundle/Resources/config/routing/jardins.yml"
        prefix:   /jardins

baby_sitting_offre:
        resource: "@BabySittingBundle/Resources/config/routing/offre.yml"
        prefix:   /offre

baby_sitting_demande:
        resource: "@BabySittingBundle/Resources/config/routing/demande.yml"
        prefix:   /demande

baby_sitting_imagepub:
        resource: "@BabySittingBundle/Resources/config/routing/imagepub.yml"
        prefix:   /imagepub

baby_sitting_localjardin:
        resource: "@BabySittingBundle/Resources/config/routing/localjardin.yml"
        prefix:   /localjardin

baby_sitting_homepage:
    path:     /
    defaults: { _controller: BabySittingBundle:Default:index }
